name: Publish Npm Package
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    url: https://www.npmjs.com/package/@spencerlepine/connect-chat-frontend-components
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Create .npmrc
        run: |
          touch .npmrc
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - run: npm install

      - run: npm run release

      - run: npm publish --access public
